if(INCLUDE__THINGY52)

get_filename_component(_tmp_source_dir "${THINGY52__BASE_DIR}/" ABSOLUTE)

include_directories(${_tmp_source_dir}/include/ble_services)
include_directories(${_tmp_source_dir}/include/board)
include_directories(${_tmp_source_dir}/include/drivers)
include_directories(${_tmp_source_dir}/include/macros)
include_directories(${_tmp_source_dir}/include/modules)
include_directories(${_tmp_source_dir}/include/util)

include_directories(${_tmp_source_dir}/libs/bv32fp-1.2)
include_directories(${_tmp_source_dir}/libs/dvi_adpcm)
include_directories(${_tmp_source_dir}/libs/eMD6/core/driver/eMPL)
include_directories(${_tmp_source_dir}/libs/eMD6/core/driver/include)
include_directories(${_tmp_source_dir}/libs/eMD6/core/driver/nrf52)
include_directories(${_tmp_source_dir}/libs/eMD6/core/eMPL-hal)
include_directories(${_tmp_source_dir}/libs/eMD6/core/mllite)
include_directories(${_tmp_source_dir}/libs/eMD6/core/mpl)
include_directories(${_tmp_source_dir}/libs/sr3_audio)
include_directories(${_tmp_source_dir}/libs/vocal_anr)

set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/a2lsp.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/allpole.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/allzero.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/autocor.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/bitpack.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/bvplc.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/cmtables.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/coarptch.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/decoder.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/encoder.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/excdec.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/excquan.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/fineptch.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/gaindec.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/gainquan.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/levdur.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/levelest.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/lsp2a.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/lspdec.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/lspquan.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/ptdec.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/ptquan.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/stblchck.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/stblzlsp.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/tables.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/bv32fp-1.2/utility.c)

set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/dvi_adpcm/dvi_adpcm.c)

set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/driver/eMPL/inv_mpu_dmp_motion_driver.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/driver/eMPL/inv_mpu.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/driver/nRF52/log_nrf52.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/eMPL-hal/eMPL_outputs.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/data_builder.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/hal_outputs.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/message_layer.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/ml_math_func.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/mlmath.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/mpl.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/results_holder.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/start_manager.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/eMD6/core/mllite/storage_manager.c)

set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/sr3_audio/drv_audio_anr.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/sr3_audio/drv_audio_coder_adpcm.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/sr3_audio/drv_audio_coder_bv32fp.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/sr3_audio/drv_audio_coder_opus.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/sr3_audio/drv_audio_dsp.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/libs/sr3_audio/drv_audio_pdm.c)

set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_acc_lis3dh.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_bh1745.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_ccs811.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_color.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_ext_gpio.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_ext_light.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_gas_sensor.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_hts221.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_humidity.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_lps22hb.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_mic.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_motion.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_mpu9250.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_pressure.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_speaker.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/drivers/drv_sx1509.c)

# set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/util/advertiser_beacon_timeslot.c)
# set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/util/nrf_dfu_flash_buttonless.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/util/support_func.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/util/sx150x_led_drv_calc.c)
set(PROJECT_SOURCES ${PROJECT_SOURCES} ${_tmp_source_dir}/source/util/twi_manager.c)


#MPL library
find_library(LIBMPLLIB mpllib ${_tmp_source_dir}/libs/eMD6/core/mpl)
set(PROJECT_LIBRARIES ${LIBMPLLIB} ${PROJECT_LIBRARIES})

find_library(VOCAL_ANR_GCC vocal_anr_gcc ${_tmp_source_dir}/libs_vocal_anr)
set(PROJECT_LIBRARIES ${LIBMPLLIB} ${PROJECT_LIBRARIES})

endif(INCLUDE__THINGY52)


